name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check clang
        run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code

      - name: Build
        run: make lib

      - name: Tests
        run: make test && time seq 100 | xargs -I{} -n 1 -P 1 ./converter-test